Repository 1e5i-Shark/algobaro-fe, pull requests merged in 2024-02, with the labels that each got.

#1 프로젝트 초기 설정
  .eslintrc.json
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  .gitignore
  .gitmessage.txt
  .husky/pre-commit
  .husky/pre-push
  .prettierrc
  .stylelintrc
  README.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/assets/.gitkeep
  src/components/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/main.tsx
  src/pages/.gitkeep
  src/routes/.gitkeep
  src/services/.gitkeep
  src/store/.gitkeep
  src/styles/.gitkeep
  src/types/.gitkeep
  src/utils/.gitkeep
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: CHORE

#7 [✨feat]: zustand 초기 설정 및 예시 store 생성
  .gitmessage.txt
  src/store/.gitkeep
  src/store/GlobalStore/index.ts
  src/store/GlobalStore/type.ts
Labels: FEAT

#6 [✨feat]: 테마 초기 설정
  src/components/.gitkeep
  src/components/ThemeContext.tsx
  src/hooks/.gitkeep
  src/hooks/useLocalStorage.ts
  src/hooks/useTheme.ts
  src/main.tsx
  src/styles/.gitkeep
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
Labels: FEAT, STYLE

#5 [✨feat]: 페이지 라우팅 기능 설정
  .gitmessage.txt
  src/App.tsx
  src/pages/CreateRoomPage/CreateRoomPage.style.ts
  src/pages/CreateRoomPage/CreateRoomPage.tsx
  src/pages/HomePage/HomePage.style.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/MainPage/MainPage.style.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/NotFoundPage/NotFoundPage.style.ts
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/ProblemSharePage/ProblemSharePage.style.ts
  src/pages/ProblemSharePage/ProblemSharePage.tsx
  src/pages/ProblemSolvePage/ProblemSolvePage.style.ts
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  src/pages/ProfilePage/ProfilePage.style.ts
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/RoomPage/RoomPage.style.ts
  src/pages/RoomPage/RoomPage.tsx
  src/pages/SignUpPage/SignUpPage.style.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/WelcomePage/WelcomePage.style.ts
  src/pages/WelcomePage/WelcomePage.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/routes/path.ts
Labels: FEAT

#12 [🎨design]: Reset css 적용, MUI icon 패키지 설치
  package-lock.json
  package.json
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
Labels: CHORE, DESIGN

#22 [♻️refactor]: 테마 리팩토링
  src/components/ThemeContext.tsx
  src/styles/style.d.ts
  src/styles/theme.ts
  src/types/.gitkeep
  src/types/index.ts
Labels: REFACTOR

#15 [✨feat]: 공통 컴포넌트 Avatar 구현
  src/assets/.gitkeep
  src/assets/avatar-dark.png
  src/assets/avatar-light.png
  src/components/Avatar/Avatar.style.ts
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/EditButton.tsx
  src/components/Avatar/index.ts
  src/components/index.ts
  src/styles/GlobalStyle.ts
Labels: FEAT

#17 [✨feat]: 공통 컴포넌트 Modal 구현
  src/components/Common/Modal/Modal.style.ts
  src/components/Common/Modal/Modal.tsx
  src/components/index.ts
  src/hooks/useModal.ts
  src/styles/theme.ts
Labels: FEAT, DESIGN

#31 [♻️refactor]: 테마 리팩토링
  src/components/ThemeContext.tsx
  src/components/ThemeCustomProvider.tsx
  src/components/index.ts
  src/hooks/useCustomTheme.ts
  src/hooks/useTheme.ts
  src/main.tsx
Labels: REFACTOR

#24 [✨feat]: 공통 컴포넌트 Input 구현
  package-lock.json
  package.json
  src/components/Common/Input/Input.style.ts
  src/components/Common/Input/Input.tsx
  src/types/input.ts
Labels: FEAT

#33 [✨feat]: 공통 컴포넌트 Tag 구현
  src/components/Common/Tag/Tag.style.ts
  src/components/Common/Tag/Tag.tsx
  src/components/index.ts
Labels: FEAT, DESIGN

#25 [✨feat]: Image 공통 컴포넌트
  src/components/Image/Image.style.ts
  src/components/Image/Image.tsx
  src/components/index.ts
  src/styles/theme.ts
Labels: FEAT

#21 [✨feat]: 공통 컴포넌트 Icon 구현
  src/components/Common/Icon/Icon.style.tsx
  src/components/Common/Icon/Icon.tsx
Labels: FEAT

#28 [✨feat]: Spinner 공통 컴포넌트
  src/components/Common/Spinner/Spinner.style.ts
  src/components/Common/Spinner/Spinner.tsx
  src/components/index.ts
  src/styles/theme.ts
Labels: FEAT

#34 [✨feat]: 공통 컴포넌트 Menu 구현
  src/components/Common/Menu/Menu.tsx
  src/components/Common/Menu/MenuText.ts
  src/components/index.ts
Labels: FEAT

#37 [✨feat]: 공통 컴포넌트 Message 구현
  src/components/Common/Message/Message.style.ts
  src/components/Common/Message/Message.tsx
  src/components/index.ts
Labels: FEAT

#36 [✨feat]: 공통 컴포넌트 CheckBox 구현
  src/components/Common/CheckBox/CheckBox.style.ts
  src/components/Common/CheckBox/CheckBox.tsx
Labels: FEAT

#46 [♻️refactor]: Message, Menu, Icon 리팩토링
  src/components/Common/Icon/Icon.tsx
  src/components/Common/Menu/Menu.tsx
  src/components/Common/Menu/MenuText.ts
  src/components/Common/Message/Message.tsx
Labels: REFACTOR

#39 [✨feat]: 공통 컴포넌트 EllipsisText 구현
  src/components/Common/EllipsisText/EllipsisText.style.ts
  src/components/Common/EllipsisText/EllipsisText.tsx
Labels: FEAT

#42 [♻️refactor]: Avatar 컨벤션 적용
  src/components/Common/Avatar/Avatar.style.ts
  src/components/Common/Avatar/Avatar.tsx
  src/components/Common/Avatar/EditButton.tsx
  src/components/Common/Image/Image.style.ts
  src/components/Common/Image/Image.tsx
  src/components/index.ts
Labels: REFACTOR

#41 [✨feat]: 공통 컴포넌트 DropDown 구현
  src/components/Common/DropDown/DropDown.style.ts
  src/components/Common/DropDown/DropDown.tsx
  src/components/Common/DropDown/MultiDropDown.tsx
  src/components/Common/DropDown/constant.ts
  src/components/Common/DropDown/index.ts
Labels: FEAT, DESIGN

#49 [✨feat]: 공통 컴포넌트 Header 구현
  src/components/Common/DarkModeToggleButton/DarkModeToggleButton.tsx
  src/components/Common/Header/Header.style.ts
  src/components/Common/Header/Header.tsx
  src/components/index.ts
  src/pages/MainPage/MainPage.style.ts
  src/pages/MainPage/MainPage.tsx
  src/styles/theme.ts
Labels: FEAT, DESIGN

#50 [🐛fix]: Router 경로 수정
  src/components/Common/Header/PSHeader.tsx
  src/pages/Layout.tsx
  src/routes/CheckUserLogin.ts
  src/routes/PrivateRoute.tsx
  src/routes/index.tsx
Labels: FIX

#56 [🎨design]: 전역 레이아웃 높이 설정
  src/components/Common/Header/Header.tsx
  src/components/Common/ThemeModeToggleButton/ThemeModeToggleButton.tsx
  src/components/index.ts
  src/pages/Layout/Layout.style.ts
  src/pages/Layout/Layout.tsx
  src/pages/index.ts
  src/routes/index.tsx
Labels: DESIGN

#57 [🐛fix]: 아바타 기본이미지 이슈 해결
  public/assets/avatar-dark.png
  public/assets/avatar-light.png
  src/components/Common/Avatar/Avatar.style.ts
Labels: FIX

#59 [✨feat]: 공용 API 인스턴스 config 및 인터셉트 설정 추가
  src/services/.gitkeep
  src/services/axiosInstance.ts
  src/services/handleAxiosError.ts
  src/types/api.ts
Labels: FEAT

#61 [🐛fix]: 공용 컴포넌트 Input 스타일 이슈 해결
  src/components/Common/ErrorMessage/ErrorMessage.style.ts
  src/components/Common/ErrorMessage/ErrorMessage.tsx
  src/components/Common/Input/Input.style.ts
  src/components/Common/Input/Input.tsx
  src/components/index.ts
  src/types/input.ts
Labels: FIX, DESIGN

#62 [🐛fix]: axiosInstance 파일 내 로컬 스토리지 JSON 파싱 취소 및 일부 수정사항 적용
  src/services/axiosInstance.ts
Labels: FIX

#51 [✨feat]: Login Form 구현
  src/components/Common/Button/Button.style.ts
  src/components/Common/Input/Input.style.ts
  src/components/Common/Input/Input.tsx
  src/components/LoginForm/LoginForm.style.ts
  src/components/LoginForm/LoginForm.tsx
  src/components/LoginForm/loginConstants.ts
  src/routes/CheckUserLogin.ts
  src/routes/PrivateRoute.tsx
  src/services/Auth/index.ts
  src/services/Auth/signIn.ts
  src/services/apiEndpoint.ts
  src/types/input.ts
Labels: FEAT, DESIGN
