Repository 1e5i-Shark/algobaro-fe, pull requests merged in 2024-03, with the labels that each got.

#64 [♻️refactor]: signIn 함수에 대한 useMutation 훅(useAuth) 구현 리팩토링
  src/components/LoginForm/LoginForm.tsx
  src/constants/localStorageKey.ts
  src/hooks/Api/type.ts
  src/hooks/Api/useAuth.ts
  src/routes/CheckUserLogin.ts
  src/services/Auth/signIn.ts
  src/services/axiosInstance.ts
Labels: REFACTOR

#65 [🐛fix]: Icon 컴포넌트 오류 수정
  src/components/Common/Icon/Icon.style.tsx
Labels: FIX

#63 [✨feat]: 방 생성 페이지 구현
  package-lock.json
  package.json
  src/components/Common/DropDown/DropDown.tsx
  src/components/Common/EllipsisText/EllipsisText.style.ts
  src/components/Common/Header/Header.style.ts
  src/components/Common/Input/Input.style.ts
  src/components/Common/Tag/Tag.tsx
  src/components/CreateRoom/CreateTagInput/CreateTagInput.style.ts
  src/components/CreateRoom/CreateTagInput/CreateTagInput.tsx
  src/components/CreateRoom/TitleWithAsterisk/TitleWithAsterisk.style.ts
  src/components/CreateRoom/TitleWithAsterisk/TitleWithAsterisk.tsx
  src/components/index.ts
  src/constants/room.ts
  src/hooks/useRooms.ts
  src/pages/CreateRoomPage/CreateRoomPage.style.ts
  src/pages/CreateRoomPage/CreateRoomPage.tsx
  src/pages/Layout/Layout.style.ts
  src/services/Room/createRoom.ts
  src/services/apiEndpoint.ts
  src/styles/theme.ts
Labels: FEAT, DESIGN

#77 [✨feat]: 회원가입 기능 및 레이아웃 구현
  src/components/Common/Input/Input.tsx
  src/components/LoginForm/LoginForm.tsx
  src/components/LoginForm/loginConstants.ts
  src/constants/.gitkeep
  src/constants/formValidation.ts
  src/hooks/Api/type.ts
  src/hooks/Api/useAuth.ts
  src/hooks/Api/useMembers.ts
  src/pages/SignUpPage/SignUpPage.style.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/pages/WelcomePage/WelcomePage.tsx
  src/services/Auth/index.ts
  src/services/Auth/signIn.ts
  src/services/Auth/signUp.ts
  src/services/Auth/type.ts
  src/services/apiEndpoint.ts
  src/services/handleAxiosError.ts
  src/types/input.ts
Labels: FEAT, DESIGN

#76 [🐛fix]: Image 컴포넌트 CSS 수정
  src/components/Common/Image/Image.style.ts
  src/components/Common/Image/Image.tsx
Labels: FIX

#83 [🐛fix]: 기존 Modal 공통 컴포넌트 버그 해결 및 업그레이드
  src/components/Common/Input/Input.tsx
  src/components/Common/Modal/Modal.style.ts
  src/components/Common/Modal/Modal.tsx
  src/pages/WelcomePage/WelcomePage.tsx
Labels: FIX, FEAT

#84 [♻️refactor]: Modal 컴포넌트의 styled 컴포넌트 컨벤션 적용 및 삼항연산자를 &&로 대체
  src/components/Common/Input/Input.tsx
  src/components/Common/Modal/Modal.style.ts
  src/components/Common/Modal/Modal.tsx
  src/pages/WelcomePage/WelcomePage.tsx
Labels: REFACTOR

#67 [✨feat]: 문제 풀이 페이지 타이머 구현, 종료 모달 연동
  src/components/Common/Timer/Timer.style.ts
  src/components/Common/Timer/Timer.tsx
  src/components/ProblemSolve/Timer/Timer.style.ts
  src/components/ProblemSolve/Timer/Timer.tsx
  src/components/index.ts
  src/pages/ProblemSolvePage/ProblemEndModal/ProblemEndModal.style.ts
  src/pages/ProblemSolvePage/ProblemEndModal/ProblemEndModal.tsx
  src/pages/ProblemSolvePage/ProblemSolvePage.style.ts
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.style.ts
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.tsx
Labels: FEAT, DESIGN

#87 [✨feat]: Pagination 공통 컴포넌트 구현
  src/components/Common/Pagination/Pagination.tsx
  src/components/index.ts
Labels: FEAT

#88 [✨feat]: 공동 편집 코드 에디터 호환성 테스트
  package-lock.json
  package.json
  src/components/IDE/CodeEditor/CodeEditor.style.ts
  src/components/IDE/CodeEditor/CodeEditor.tsx
  src/components/IDE/CodeEditor/CodeEditorLibs.ts
  src/components/IDE/CodeEditor/utils.ts
  src/components/index.ts
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  tsconfig.json
  vite.config.ts
Labels: FEAT

#73 [✨feat]: 코드 풀이 페이지 레이아웃 구현
  package-lock.json
  package.json
  src/components/Common/Header/PSHeader.style.ts
  src/components/Common/Header/PSHeader.tsx
  src/components/Common/ResizeHandle/ResizeHandle.style.ts
  src/components/Common/ResizeHandle/ResizeHandle.tsx
  src/components/Common/Timer/Timer.tsx
  src/components/IDE/CodeEditor/CodeEditor.tsx
  src/components/index.ts
  src/hooks/useProblemSolve.ts
  src/pages/ProblemSolvePage/ProblemEndModal/ProblemEndModal.style.ts
  src/pages/ProblemSolvePage/ProblemExecution/ProblemExecution.style.ts
  src/pages/ProblemSolvePage/ProblemExecution/ProblemExecution.tsx
  src/pages/ProblemSolvePage/ProblemSection/ProblemSection.style.ts
  src/pages/ProblemSolvePage/ProblemSection/ProblemSection.tsx
  src/pages/ProblemSolvePage/ProblemSolvePage.style.ts
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.style.ts
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.tsx
  src/pages/ProblemSolvePage/constants.ts
  src/services/ProblemSolve/compile.ts
  src/services/ProblemSolve/submission.ts
  src/services/apiEndpoint.ts
  src/styles/theme.ts
Labels: FEAT, DESIGN

#71 [✨feat]: Main 페이지 UI 구현
  src/components/Common/CheckBox/CheckBox.style.ts
  src/pages/HomePage/DummyData/DummyData.ts
  src/pages/HomePage/DummyData/DummyData.type.ts
  src/pages/HomePage/DummyData/index.ts
  src/pages/HomePage/HomeNav/HomeNav.style.ts
  src/pages/HomePage/HomeNav/HomeNav.tsx
  src/pages/HomePage/HomePage.style.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/HomeSection/HomeSection.style.ts
  src/pages/HomePage/HomeSection/HomeSection.tsx
Labels: FEAT, DESIGN

#92 [🐛fix]: 방 생성 페이지 API 필드 수정
  src/constants/room.ts
  src/hooks/useCreateRoom.ts
  src/hooks/useRooms.ts
  src/pages/CreateRoomPage/CreateRoomPage.tsx
  src/services/Room/createRoom.ts
Labels: FIX

#95 [✨feat]: 로그인 실패 alert 및 로그인, 회원가입 페이지 디자인 변경
  src/components/Common/Header/Header.tsx
  src/components/LoginForm/LoginForm.style.ts
  src/pages/ProfilePage/PasswordEditModal/PasswordEditModal.style.ts
  src/pages/ProfilePage/ProfileEditModal/ProfileEditModal.style.ts
  src/pages/ProfilePage/ProfilePage.style.ts
  src/pages/SignUpPage/SignUpPage.style.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/services/handleAxiosError.ts
  src/styles/GlobalStyle.ts
Labels: FEAT, DESIGN

#96 [✨feat]: 코드 공유 페이지 레이아웃 구현
  src/components/Common/Header/PSHeader.tsx
  src/components/Common/Timer/Timer.tsx
  src/constants/room.ts
  src/pages/ProblemSharePage/ProblemSharePage.style.ts
  src/pages/ProblemSharePage/ProblemSharePage.tsx
  src/pages/ProblemSharePage/UserProfileList/UserProfileList.style.ts
  src/pages/ProblemSharePage/UserProfileList/UserProfileList.tsx
  src/pages/ProblemSharePage/constants.ts
  src/pages/ProblemSharePage/type.ts
  src/pages/ProblemSolvePage/ProblemEndModal/ProblemEndModal.tsx
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.style.ts
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.tsx
  src/store/TimerStore/index.ts
Labels: FEAT, DESIGN

#74 [✨feat]: Main 페이지 구현 - 검색 필터 기능 구현
  src/components/Common/DropDown/MultiDropDown.tsx
  src/constants/logos.ts
  src/constants/queryKey.ts
  src/constants/room.ts
  src/hooks/Api/useRooms.ts
  src/pages/HomePage/DummyData/DummyData.ts
  src/pages/HomePage/DummyData/DummyData.type.ts
  src/pages/HomePage/DummyData/index.ts
  src/pages/HomePage/HomeFooter/HomeFooter.style.ts
  src/pages/HomePage/HomeFooter/HomeFooter.tsx
  src/pages/HomePage/HomeNav/HomeNav.style.ts
  src/pages/HomePage/HomeNav/HomeNav.tsx
  src/pages/HomePage/HomePage.style.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/HomeSection/HomeSection.style.ts
  src/pages/HomePage/HomeSection/HomeSection.tsx
  src/services/Room/getRoomsList.ts
  src/services/Room/type.ts
  src/store/RoomsListStore/useFilterStore/index.ts
  src/store/RoomsListStore/useFilterStore/type.ts
  src/store/RoomsListStore/usePageStore/index.ts
  src/store/RoomsListStore/usePageStore/type.ts
  src/types/room.ts
Labels: FEAT

#78 [✨feat]: RoomPage 레이아웃 및 기본 기능 구현
  src/components/Common/Menu/MenuText.ts
  src/components/MemberCard/MemberCard.style.ts
  src/components/MemberCard/MemberCard.tsx
  src/components/MemberCard/StatusTag.tsx
  src/components/MemberCard/index.ts
  src/components/index.ts
  src/constants/queryKey.ts
  src/hooks/Api/useRooms.ts
  src/pages/RoomPage/ChatViews/ChatInput.tsx
  src/pages/RoomPage/ChatViews/ChatViews.tsx
  src/pages/RoomPage/MemberList/MemberList.tsx
  src/pages/RoomPage/RoomHeader/ModalRoom.tsx
  src/pages/RoomPage/RoomHeader/RoomHeader.tsx
  src/pages/RoomPage/RoomHeader/RoomHeaderButtons.tsx
  src/pages/RoomPage/RoomHeader/RoomHeaderInfo.tsx
  src/pages/RoomPage/RoomHeader/index.ts
  src/pages/RoomPage/RoomPage.consts.ts
  src/pages/RoomPage/RoomPage.style.ts
  src/pages/RoomPage/RoomPage.tsx
  src/pages/RoomPage/TestInfo/TestInfo.tsx
  src/services/Room/Room.ts
  src/services/Room/createRoom.ts
  src/services/apiEndpoint.ts
  src/store/MyInfoStore/index.ts
  src/store/MyInfoStore/types.ts
  src/store/RoomStore/index.ts
  src/store/RoomStore/type.ts
  src/styles/theme.ts
  src/types/index.ts
  src/types/input.ts
  src/types/myInfo.ts
Labels: FEAT

#98 [🐛fix]: Chat 배포 오류 해결
  src/hooks/chat/useMessage.ts
Labels: FIX

#100 [✨feat]: HomePage 페이지네이션, API 연동, 방 입장 기능 및 세부 사항 처리
  src/components/Common/DropDown/MultiDropDown.tsx
  src/constants/queryKey.ts
  src/hooks/Api/useRooms.ts
  src/pages/HomePage/HomeNav/HomeNav.style.ts
  src/pages/HomePage/HomeNav/HomeNav.tsx
  src/pages/HomePage/HomeNav/animatedIcon.tsx
  src/pages/HomePage/HomeNav/useStopWatch.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/HomeSection/CheckRoomPassword.tsx
  src/pages/HomePage/HomeSection/HomeSection.style.ts
  src/pages/HomePage/HomeSection/HomeSection.tsx
  src/pages/HomePage/convertValueTokey.ts
  src/services/Room/getRoomDetail.ts
  src/services/Room/type.ts
  src/store/RoomsListStore/useFilterStore/index.ts
  src/store/RoomsListStore/useFilterStore/type.ts
Labels: FEAT

#102 [✨feat]: 문제 풀이 페이지에서 크롤링한 문제 정보 표시
  src/constants/queryKey.ts
  src/hooks/Api/useProblem.ts
  src/pages/ProblemSolvePage/ProblemSection/ProblemSection.style.ts
  src/pages/ProblemSolvePage/ProblemSection/ProblemSection.tsx
  src/pages/ProblemSolvePage/ProblemSection/parseProblemInfo.ts
  src/pages/ProblemSolvePage/ProblemSolvePage.style.ts
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  src/pages/RoomPage/TestInfo/TestInfo.tsx
  src/services/Problem/getProblemInfo.ts
  src/services/apiEndpoint.ts
Labels: FEAT, DESIGN

#105 [🐛fix]: #32 Room 라우트 params 수정 및 axios 에러 해결
  src/hooks/Api/useRooms.ts
  src/hooks/useCreateRoom.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/HomeSection/HomeSection.tsx
  src/pages/RoomPage/RoomHeader/RoomHeader.tsx
  src/pages/RoomPage/RoomPage.tsx
  src/routes/index.tsx
  src/store/MessageStore/index.ts
  src/store/MessageStore/type.ts
Labels: FIX

#104 [🐛fix]: RoomPage 웹소켓 disconnect 이슈 해결
  src/pages/RoomPage/RoomHeader/RoomHeader.tsx
  src/pages/RoomPage/RoomPage.tsx
  src/store/MessageStore/index.ts
Labels: FIX

#97 [✨feat]: 코드 에디터 드롭다운 추가, compile API 연동
  src/components/Common/DateBaseTimer/DateBaseTimer.style.ts
  src/components/Common/DateBaseTimer/DateBaseTimer.tsx
  src/components/Common/DropDown/DropDown.tsx
  src/components/Common/Header/PSHeader.style.ts
  src/components/Common/Header/PSHeader.tsx
  src/components/Common/ResizeHandle/ResizeHandle.style.ts
  src/components/Common/Timer/Timer.tsx
  src/components/IDE/CodeEditor/CodeEditor.style.ts
  src/components/IDE/CodeEditor/CodeEditor.tsx
  src/components/IDE/CodeEditor/utils.ts
  src/components/index.ts
  src/constants/room.ts
  src/hooks/useProblemSolve.ts
  src/pages/ProblemSharePage/ProblemSharePage.tsx
  src/pages/ProblemSolvePage/ProblemEndModal/ProblemEndModal.style.ts
  src/pages/ProblemSolvePage/ProblemEndModal/ProblemEndModal.tsx
  src/pages/ProblemSolvePage/ProblemExecution/ProblemExecution.style.ts
  src/pages/ProblemSolvePage/ProblemExecution/ProblemExecution.tsx
  src/pages/ProblemSolvePage/ProblemSolvePage.style.ts
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.style.ts
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.tsx
  src/pages/ProblemSolvePage/constants.ts
  src/services/ProblemSolve/compile.ts
  src/services/ProblemSolve/submission.ts
  src/store/CodeEditorStore/index.ts
  src/store/TimerStore/index.ts
  src/styles/theme.ts
  src/utils/timer.ts
Labels: FEAT

#106 [✨feat]: 코드 에디터 언어별 기본값 추가 및 관련 설정 변경
  src/components/Common/DropDown/DropDown.tsx
  src/components/IDE/CodeEditor/CodeEditor.tsx
  src/components/IDE/CodeEditor/utils.ts
  src/constants/room.ts
  src/pages/ProblemSharePage/ProblemSharePage.tsx
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
Labels: FEAT

#101 [✨feat]: RoomPage 웹소켓 연결
  src/components/Common/Chat/Chat.tsx
  src/components/Common/Chat/ChatInput.tsx
  src/components/MemberCard/MemberCard.tsx
  src/hooks/Api/useRooms.ts
  src/hooks/useCreateRoom.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/HomeSection/HomeSection.tsx
  src/pages/RoomPage/ChatViews/ChatInput.tsx
  src/pages/RoomPage/ChatViews/ChatViews.tsx
  src/pages/RoomPage/MemberList/MemberList.tsx
  src/pages/RoomPage/RoomHeader/ModalRoom.tsx
  src/pages/RoomPage/RoomHeader/RoomHeader.tsx
  src/pages/RoomPage/RoomHeader/RoomHeaderButtons.tsx
  src/pages/RoomPage/RoomHeader/RoomHeaderInfo.tsx
  src/pages/RoomPage/RoomPage.style.ts
  src/pages/RoomPage/RoomPage.tsx
  src/pages/RoomPage/TestInfo/TestInfo.tsx
  src/pages/RoomPage/findMyRoomData.ts
  src/routes/index.tsx
  src/services/Room/Room.ts
  src/services/apiEndpoint.ts
  src/store/MessageStore/index.ts
  src/store/MessageStore/type.ts
  src/store/MyInfoStore/index.ts
  src/store/RoomStore/index.ts
  src/store/RoomStore/type.ts
Labels: FEAT

#112 [✨feat]: 문제 풀이 페이지 테스트 케이스 채점 및 제출 모달 추가
  package-lock.json
  package.json
  src/components/Common/Header/PSHeader.tsx
  src/hooks/Api/useProblem.ts
  src/hooks/useProblemSolve.ts
  src/pages/ProblemSharePage/ProblemSharePage.tsx
  src/pages/ProblemSolvePage/ProblemEndModal/ProblemEndModal.tsx
  src/pages/ProblemSolvePage/ProblemExecution/ProblemExecution.style.ts
  src/pages/ProblemSolvePage/ProblemExecution/ProblemExecution.tsx
  src/pages/ProblemSolvePage/ProblemSection/ProblemSection.tsx
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  src/pages/ProblemSolvePage/ProblemSubmitModal/ProblemSubmitModal.style.ts
  src/pages/ProblemSolvePage/ProblemSubmitModal/ProblemSubmitModal.tsx
  src/pages/ProblemSolvePage/ProblemSubmitModal/lottie/fail-lottie.json
  src/pages/ProblemSolvePage/ProblemSubmitModal/lottie/success-lottie.json
  src/pages/RoomPage/RoomHeader/ModalRoom.tsx
  src/pages/RoomPage/TestInfo/TestInfo.tsx
  src/services/ProblemSolve/submission.ts
Labels: FEAT

#111 [✨feat]: 문제 풀이 공유 페이지 API 연동
  src/constants/queryKey.ts
  src/hooks/Api/useRooms.ts
  src/hooks/Api/useSolves.ts
  src/pages/ProblemSharePage/ProblemSharePage.style.ts
  src/pages/ProblemSharePage/ProblemSharePage.tsx
  src/pages/ProblemSharePage/UserProfileList/UserProfileList.tsx
  src/pages/ProblemSharePage/constants.ts
  src/services/Solve/getSolvedResult.ts
  src/services/Solve/index.ts
  src/services/Solve/type.ts
  src/services/apiEndpoint.ts
Labels: FEAT

#113 [✨feat]: 코드 에디터 붙여넣기 방지 코드 추가
  src/components/IDE/CodeEditor/CodeEditor.tsx
  src/store/CodeEditorStore/index.ts
Labels: FEAT

#115 [✨feat]: ProblemShare 웹소켓 연결
  src/components/Common/Chat/Chat.tsx
  src/components/Common/Header/PSHeader.tsx
  src/components/IDE/CodeEditor/CodeEditor.tsx
  src/components/MemberCard/MemberCard.tsx
  src/hooks/useProblemSolve.ts
  src/pages/HomePage/HomeSection/HomeSection.tsx
  src/pages/ProblemSharePage/ProblemSharePage.style.ts
  src/pages/ProblemSharePage/ProblemSharePage.tsx
  src/pages/ProblemSharePage/UserProfileList/UserProfileList.style.ts
  src/pages/RoomPage/MemberList/MemberList.tsx
  src/pages/RoomPage/RoomHeader/RoomHeaderButtons.tsx
  src/pages/RoomPage/RoomPage.style.ts
  src/pages/RoomPage/RoomPage.tsx
  src/pages/RoomPage/TestInfo/TestInfo.tsx
  src/routes/PrivateRoute.tsx
  src/store/MessageStore/index.ts
  src/store/MessageStore/type.ts
  src/store/RoomStore/index.ts
  src/store/RoomStore/type.ts
Labels: FEAT

#117 [✨feat]: Status 드롭다운 추가, API에 맞춰서 레이아웃 수정
  src/pages/ProblemSharePage/ProblemSharePage.style.ts
  src/pages/ProblemSharePage/ProblemSharePage.tsx
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  src/pages/ProblemSolvePage/ProblemSubmitModal/ProblemSubmitModal.style.ts
  src/pages/ProblemSolvePage/ProblemSubmitModal/ProblemSubmitModal.tsx
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.tsx
  src/pages/ProblemSolvePage/constants.ts
  src/services/ProblemSolve/submission.ts
Labels: FEAT

#122 [🐛fix]: 문제 풀이 페이지 1차 QA 피드백 적용하기
  src/components/Common/DateBaseTimer/DateBaseTimer.tsx
  src/components/IDE/CodeEditor/CodeEditor.style.ts
  src/components/IDE/CodeEditor/CodeEditor.tsx
  src/components/IDE/CodeEditor/utils.ts
  src/hooks/Api/useProblem.ts
  src/hooks/Api/useSolves.ts
  src/pages/CreateRoomPage/CreateRoomPage.style.ts
  src/pages/ProblemSharePage/ProblemSharePage.style.ts
  src/pages/ProblemSharePage/ProblemSharePage.tsx
  src/pages/ProblemSolvePage/ProblemSection/ProblemSection.style.ts
  src/pages/ProblemSolvePage/ProblemSolvePage.style.ts
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  src/pages/ProblemSolvePage/ProblemSubmitModal/ProblemSubmitModal.tsx
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.style.ts
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.tsx
  src/pages/ProblemSolvePage/constants.ts
  src/pages/RoomPage/RoomPage.tsx
  src/services/ProblemSolve/submission.ts
  src/services/Solve/type.ts
  src/store/CodeEditorStore/index.ts
  src/store/MessageStore/index.ts
  src/store/RoomStore/index.ts
  src/store/TimerStore/index.ts
  src/types/room.ts
  src/utils/convertDate.ts
Labels: FIX, REFACTOR

#125 [🐛fix]: RoomAccessType 변경 시 참여자들에게는 즉시 적용되지 않던 문제 (임시)
  src/hooks/Api/useRooms.ts
  src/pages/RoomPage/RoomPage.tsx
Labels: FIX

#126 [🐛fix]: HomePage 피드백 사안 적용
  src/components/Common/DropDown/MultiDropDown.tsx
  src/hooks/useCreateRoom.ts
  src/hooks/useValidateEnter.ts
  src/pages/HomePage/HomeNav/HomeNav.tsx
  src/pages/HomePage/HomeNav/useStopWatch.ts
  src/pages/HomePage/HomeSection/CheckRoomPassword.tsx
  src/pages/HomePage/HomeSection/HomeSection.tsx
  src/services/Room/validateEnter.ts
Labels: FIX, FEAT

#127 [✨feat]: 테스트 케이스 입력 Input 구현 및 제출 모달에서 테스트 결과 표시 기능 다시 추가
  src/hooks/useProblemSolve.ts
  src/pages/ProblemSolvePage/ProblemSolvePage.style.ts
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  src/pages/ProblemSolvePage/ProblemSubmitModal/ProblemSubmitModal.style.ts
  src/pages/ProblemSolvePage/ProblemSubmitModal/ProblemSubmitModal.tsx
  src/pages/ProblemSolvePage/TestCaseInput/TestCaseInput.style.ts
  src/pages/ProblemSolvePage/TestCaseInput/TestCaseInput.tsx
  src/pages/ProblemSolvePage/constants.ts
  src/services/ProblemSolve/testCaseSubmission.ts
  src/services/apiEndpoint.ts
  src/store/CodeEditorStore/index.ts
Labels: FEAT, DESIGN

#128 [🐛fix]: RoomPage QA 피드백 적용
  src/components/Common/Chat/Chat.tsx
  src/components/Common/Header/PSHeader.tsx
  src/components/Common/Message/Message.tsx
  src/hooks/Api/useRooms.ts
  src/pages/ProblemSharePage/ProblemSharePage.tsx
  src/pages/ProblemSolvePage/ProblemSolvePage.tsx
  src/pages/RoomPage/RoomHeader/RoomHeader.tsx
  src/pages/RoomPage/RoomHeader/RoomHeaderInfo.tsx
  src/pages/RoomPage/RoomHeader/RoomUpdateModal.tsx
  src/pages/RoomPage/RoomHeader/index.ts
  src/pages/RoomPage/RoomPage.style.ts
  src/pages/RoomPage/RoomPage.tsx
  src/pages/RoomPage/TestInfo/TestInfo.tsx
  src/store/MessageStore/index.ts
  src/styles/GlobalStyle.ts
Labels: FIX, FEAT

#123 [✨feat]: 히스토리 상세 모달 구현 및 리스트 디자인 수정
  src/components/Common/Header/Header.tsx
  src/constants/queryKey.ts
  src/hooks/Api/useSolves.ts
  src/pages/ProblemSolvePage/constants.ts
  src/pages/ProfilePage/HistoryDetailModal/HistoryDetailModal.style.ts
  src/pages/ProfilePage/HistoryDetailModal/HistoryDetailModal.tsx
  src/pages/ProfilePage/HistoryDetailModal/languageConstant.ts
  src/pages/ProfilePage/ProfilePage.style.ts
  src/pages/ProfilePage/ProfilePage.tsx
  src/services/Member/editMyImage.ts
  src/services/Member/editMyInfo.ts
  src/services/Member/editMyPassword.ts
  src/services/Solve/getSolvedDetail.ts
  src/services/Solve/getSolvedHistoryList.ts
  src/services/Solve/getSolvedResult.ts
  src/services/Solve/type.ts
  src/services/apiEndpoint.ts
  src/utils/convertDate.ts
Labels: FEAT, DESIGN

#119 [♻️refactor]: 아바타 isSelect 기능 추가
  src/components/Common/Avatar/Avatar.style.ts
  src/components/Common/Avatar/Avatar.tsx
  src/pages/ProblemSharePage/UserProfileList/UserProfileList.tsx
Labels: REFACTOR, FEAT

#133 [✨feat]: Logo, Favicon, Font 적용
  index.html
  public/assets/logo-text.png
  public/assets/logo.png
  public/favicon.ico
  src/components/Common/Header/Header.tsx
  src/components/Common/Image/Image.style.ts
  src/components/Common/Image/Image.tsx
  src/pages/WelcomePage/WelcomePage.style.ts
  src/pages/WelcomePage/WelcomePage.tsx
  src/styles/GlobalStyle.ts
Labels: FEAT

#134 [🐛fix]: Chat 컴포넌트 채팅 메세지 중복 출력 이슈 해결
  src/components/Common/Chat/Chat.tsx
Labels: FIX

#139 [✨feat]: WelcomePage scroll animation 구현
  src/pages/WelcomePage/WelcomePage.style.ts
  src/pages/WelcomePage/WelcomePage.tsx
Labels: FEAT, DESIGN

#135 [🐛fix]: 인증 관련 에러 로직 alert 및 한국 시간 표시 에러 이슈 해결
  src/components/Common/Avatar/Avatar.tsx
  src/components/Common/Header/Header.tsx
  src/components/LoginForm/LoginForm.style.ts
  src/components/LoginForm/LoginForm.tsx
  src/hooks/Api/useAuth.ts
  src/pages/SignUpPage/SignUpPage.tsx
  src/services/handleAxiosError.ts
  src/utils/convertDate.ts
Labels: FIX, REFACTOR

#136 [✨feat]: alert 함수를 toast로 교체
  package-lock.json
  package.json
  src/components/IDE/CodeEditor/CodeEditor.tsx
  src/components/ToastProvider.tsx
  src/main.tsx
  src/pages/HomePage/HomeNav/HomeNav.tsx
  src/pages/ProblemSolvePage/ProblemSubmitModal/ProblemSubmitModal.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/RoomPage/RoomHeader/RoomHeaderInfo.tsx
  src/pages/RoomPage/RoomHeader/RoomUpdateModal.tsx
  src/pages/RoomPage/RoomPage.tsx
  src/services/handleAxiosError.ts
  src/utils/toastify.ts
Labels: FEAT

#142 [✨feat]: Meta 및 OG tag 설정
  index.html
  public/assets/thumbnail.png
Labels: FEAT

#141 [✨feat]: WelcomePage 소개란 애니메이션 적용
  index.html
  package-lock.json
  package.json
  public/assets/moreDetail/HomePage.webp
  public/assets/moreDetail/RoomPage.webp
  public/assets/moreDetail/SharePage.webp
  public/assets/moreDetail/SolvePage.webp
  src/components/IDE/CodeEditor/CodeEditor.style.ts
  src/pages/ProblemSolvePage/ProblemSection/ProblemSection.style.ts
  src/pages/ProblemSolvePage/ProblemTimer/ProblemTimer.tsx
  src/pages/WelcomePage/WelcomePage.style.ts
  src/pages/WelcomePage/WelcomePage.tsx
  src/styles/theme.ts
  src/utils/.gitkeep
Labels: FEAT, DESIGN
